GOOGLE_WORKSPACE_SEARCH_TERMS = [
    # data pipelines
    "data",
    "connector",
    "export",
    "import",
    "database",
    "merge",
    "api",
    "sync",
    "zapier",
    "stitchdata",
    "fivetran",
    # general productivity
    "email",
    "mail merge",
    "calendar",
    "docs",
    "sheets",
    "slides",
    "reports",
    "diagram",
    "forms",
    "trello",
    "quiz",
    "automatic",
    # ADS
    "ads",
    "analytics",
    "social",
    "seo",
    "ppc",
    "facebook",
    "linkedin",
    "snapchat",
    # E-commerce
    "e-commerce",
    "shopify",
    "qr",
    # CRM
    "crm",
    "contacts",
    "salesforce",
    "hubspot",
    "zoho",
    # File management
    "pdf",
    "zip",
    "sign",
    "docusign",
    "encrypt",
    "secure",
    # Finance
    "finance",
    "accounting",
    "quickbooks",
    "stocks",
    "trading",
    # AI
    "gpt",
    "chatgpt",
    "ai",
    "translate",
    "transcribe",
]

CHROME_EXTENSION_SEARCH_TERMS = (
    [
        "Bookmark Manager",
        "Image Viewer",
        "Downloads Access",
        "URL Manager",
        "Vertical Tabs",
        "Roblox Enhancements",
        "Tab Manager",
        "Tab Saver",
        "Student Picker",
        "Ad Blocker",
        "GrowthX",
        "Kabila Wallet",
        "Maps Access",
        "Histogram Tool",
        "MajesticChrome",
        "AI Assistant",
        "Persian Web",
        "Team Names",
        "Code Styling",
        "YouTube Speeder",
        "Sports Tab",
        "Chat UI",
        "URL Loader",
        "Tabs Export",
        "Text Customize",
        "Efficient Blocker",
        "Maps Thumbnails",
        "Endpoint Security",
        "Browser Security",
        "AdBlock",
        "AdBlocker",
        "Social AdBlock",
        "Password Manager",
        "Privacy Checker",
        "Scam Detection",
        "Anti-Tracking",
        "Adblocking",
        "Phishing Protection",
        "VPN Control",
        "Pop-up Blocker",
        "Online Security",
        "Malware Blocker",
        "Email Masking",
        "Password Security",
        "Crypto Protection",
        "User Agent",
        "Crypto Security",
        "Interceptor",
        "Privacy Guard",
        "Password Generator",
        "User Security",
        "Privacy Scanner",
        "Random Email",
        "Password Manager",
        "Privacy Settings",
        "Browser Security",
        "Blockchain Security",
        "Secure Links",
        "AI Safety",
        "Message Privacy",
        "Web3 Safety",
        "Private Search",
        "ChatGPT DLP",
    ]
    + [
        "Location Notifications",
        "Flight Deals",
        "Booking Copier",
        "Travel Guide",
        "Vacation Bookings",
        "Da Nang News",
        "Flight Info",
        "City Attractions",
        "Taxi Booking",
        "Visa Appointment",
        "Visa Reservation",
        "Points Calculator",
        "Quran Tab",
        "Fundraiser Distribution",
        "Tree Planting",
        "Live Music",
        "Journal Tracker",
        "NSFW Blocker",
        "Self Tracking",
        "Break Reminder",
        "Well-being Tips",
        "Exercise Discovery",
        "Mute Keywords",
        "Mindfulness Reminder",
        "Inspirational Quotes",
        "Wisdom Wheel",
        "Biblical Insights",
        "Break Alerts",
        "Affirmation Creator",
        "Mood Booster",
        "YouTube Volume",
        "Blue Light Filter",
        "Financial Tool",
        "Mental Health",
        "Aion Extension",
        "Calm Tab",
        "Hydration Reminder",
        "Adhkar Popups",
        "Nur Extension",
        "Health Tips",
        "Daily Tarot",
        "DeedDiary",
        "Dark Mode",
        "Text Speech",
        "Video Speed",
        "Right Click Unblock",
        "Font Finder",
        "Roblox Tools",
        "Social AdBlocker",
        "Sound Equalizer",
        "PiP Mode",
        "VPN Access",
        "Text Translator",
        "Roblox Enhancement",
        "Web Reader",
        "Flash Player",
        "Talking Keyboard",
        "Cookie Warning",
        "Korean Localizer",
        "Pokémon Showdown",
        "Accessibility Tool",
        "Asset Portal",
        "Playlist Duration",
        "Payday Loans",
        "Text Speech",
        "Meet Zoom",
        "RTL Alignment",
        "Forum Features",
        "KLMS Redesign",
        "Video Control",
        "HR Glossary",
        "Zalo Tools",
        "PJE Browser",
        "Cookie Management",
        "File Verification",
        "Tab Manager",
        "Tabs Organizer",
        "Voice Expansion",
        "New Tab",
        "Video Downloader",
        "Cookie Acceptance",
        "New Tab Dashboard",
        "Calendar Dark Mode",
        "Cẩm nang du lịch",
        "Công cụ tin tức",
        "BOKA DIN TAXI",
        "Быстрая запись",
        "Помощь в резервировании",
        "나랏말이 POE",
        "Tự động thêm bạn zalo",
        "Extensão gratuita",
        "Központi Azonosító",
    ]
    + [
        "Rate Alerts",
        "Chinese Tools",
        "News Access",
        "Klarna Shopping",
        "Save Online",
        "Cash Back",
        "Pricing History",
        "LetyShops Cashback",
        "Seller Protection",
        "Coupon Finder",
        "Cuponomia Alerts",
        "Online Coupons",
        "Price Comparison",
        "Steam Augmentation",
        "Miles Activation",
        "BigGo Assistant",
        "Universal List",
        "Cently Savings",
        "Cashrewards Alert",
        "Shopping Simplified",
        "Aliexpress Tools",
        "Price Comparison",
        "Social Blade",
        "Picodi Savings",
        "ID.me Discounts",
        "Zola Registry",
        "Smarty Coupons",
        "DSers Sync",
        "Trendyol Discount",
        "Gift Cards",
        "Dropshipping Tool",
        "Loyalty Connection",
        "Shopping Tab",
        "Duos Discount",
        "Facebook Cartzy",
        "AliExpress Search",
        "Social Media Saver",
        "SoleBack Cashback",
        "KAERU Tool",
        "Poly CashBack",
        "Shopping Lists",
        "Kupp Alerts",
        "Naseem Discount",
        "Trendyol Coupon",
        "Scout Helper",
        "ZeroCarbon Impact",
        "Airport Discount",
        "Alibo.vn",
        "Skype Meetings",
        "WhatsApp Tools",
        "Twitch Enhancement",
        "Content Tool",
        "Unblock Sites",
        "Sync Play",
        "Hidden Messages",
        "Link Generator",
        "Instagram Browser",
        "Instagram Scheduler",
        "Web Annotation",
        "YouTube Sync",
        "Instagram Downloader",
        "Facebook Fixer",
        "LinkedIn Prospecting",
        "Meet Attendance",
        "Instagram Desktop",
        "Houzz Ideas",
        "Twitter Enhancer",
        "WhatsApp AI",
        "Facebook Downloader",
        "Facebook AI",
        "Chrome Tab Closer",
        "Instagram Leads",
        "Instagram Leads Pro",
        "Friend Expander",
        "Profile NFT",
        "Ọc Ọc",
        "BluLink CRM",
        "AI Posting Helper",
        "Forocoches",
        "WhatsApp Scraper",
        "Selling Collab",
        "Custom Messages",
        "YouTube Localization",
        "Better Choices",
        "SAKUGABOORU Enhancer",
        "LinkedIn Automation",
        "Alchemy Software",
        "Travel Ideas",
        "Flight Comparison",
        "Wanderlust App",
        "Hotel Discounts",
        "Interactive Maps",
        "Hotel Comparison",
        "Airbnb Comparison",
        "Luxury Travel",
        "Rental Comparison",
        "Hotel Search",
        "Travel Helper",
        "Hotel Direct Price",
        "Radio Wanderlust",
        "Education District",
    ]
    + [
        "Form Filler",
        "xPath Plugin",
        "Open Source Design",
        "SEO Report",
        "nofollow Detector",
        "Research Access",
        "Android Downloader",
        "Docs Analyzer",
        "SEO Tools",
        "Tag Manager Size",
        "NFT Shopping",
        "Loadium Extension",
        "Webflow Productivity",
        "Message Connector",
        "Browser Mockup",
        "ACF Helper",
        "Tags Helper",
        "Freelancer Rank",
        "HubSpot Features",
        "Javascript Injector",
        "Ad Analysis",
        "RevenueBot Functionality",
        "Analytics Inspector",
        "Functionize Tool",
        "Screenshot Tool",
        "Input Tools",
        "Translation Viewer",
        "Developer Toolbox",
        "Citation Generator",
        "Translator Dictionary",
        "Scholar Access",
        "Citations Generator",
        "Attendance Saver",
        "Language Learning",
        "Web Annotation",
        "Lingualeo Translator",
        "LingQ Importer",
        "Trancy Subtitles",
        "Video Notes",
        "Academic Proofreading",
        "Flashcard Importer",
        "Knowledge Base",
        "Recipe Converter",
        "Translation Comparison",
        "한글 자막",
        "Literary Sites",
        "MVP Experience",
        "Turkmen Dictionary",
        "Canvas Tools",
        "Math Tutor",
        "Educational Materials",
        "UCSB Helper",
        "Language Learning",
        "Georgian Schedule",
        "Video Looper",
        "ZTM Extension",
        "Blockchain Security",
        "Search ChatGPT",
        "Learning Companion",
        "Kanji Highlighter",
        "Grammar Fix",
        "Grade Calculator",
        "Danmaku Display",
        "NCERT Books",
        "Bangla Translation",
        "NCERT Books Hindi",
        "Site Logging",
        "Math Solutions",
        "Ferrari Cursor",
        "Music Identifier",
        "Definitions Viewer",
        "42 Enhancements",
        "Twitch Enhancer",
        "Multisig Wallet",
        "PDF Tools",
        "Ecosia Search",
        "Screenshot Tool",
        "Content Summarizer",
        "Printer-Friendly Pages",
        "Email Finder",
        "Pitch Shifter",
        "CS:GO Analyzer",
        "Captcha Solver",
        "Canvas Features",
        "AI Agent Chrome",
        "Job Applications",
        "Trading Companion",
        "Youtube Enhancer",
        "B2B Contacts",
        "PandaWallet",
        "Meeting Controls",
        "AI Video Maker",
        "Premier Search",
        "Twitter Plugin",
        "Contact Finder",
        "Job Tracker",
        "Credentials Wallet",
        "Amazon Extension",
        "AVM Wallet",
        "Data Insights",
        "Product Analysis",
        "AI Youtube Summarizer",
        "Auto Trading",
        "Privacy Search",
        "Wildberries Tools",
        "Web3 Search",
        "Ad Blocker",
        "Remote Desktop",
        "Zoom Scheduler",
        "Google Keep",
        "Search Results",
        "Pinterest Save",
        "Google Drive Save",
        "Google Office",
        "Speedtest",
        "ChatGPT Access",
        "Digital Signature",
        "GenAI Tools",
        "Volume Booster",
        "Notion Clipper",
        "Steam Enhancer",
        "Password Manager",
        "Password Storage",
        "Sound Booster",
        "PDF Viewer",
        "Stanford Fun",
        "Translator",
        "Weather Forecast",
        "UI Tests",
        "Global Collector",
        "KISer Quotes",
        "Douyu Enhancer",
        "Music Links",
        "McGill Enhancer",
        "AliExpress Downloader",
        "Foodify Recipes",
        "Movie Links",
        "Candidate Sourcing",
        "Task Buddy",
        "Interactive Feedback",
        "Alibaba Search",
        "Cryptocurrency Insights",
        "Free Technologies",
        "MSDN Localization",
        "Image Download",
        "Image Download",
        "Image Info",
        "Image Downloader",
        "Sumopaint",
        "Unsplash Photos",
        "Imgur Upload",
        "Image Download",
        "Anime Wallpaper",
        "Customizable Tab",
        "Goku Wallpapers",
        "Neon Space Wallpapers",
        "Art Wallpapers",
        "Google Images",
        "Mandala Drawing",
        "Batch Downloader",
        "Photo Editor",
        "Space Images",
        "Speed Dial",
        "Content Curator",
        "Block Media",
        "Photo Editor",
        "FIFA Wallpapers",
        "One Piece Wallpapers",
        "Digital Art",
        "Blur Disable",
        "Color Tool",
        "Cartoonize Photo",
        "Outdoor Inspiration",
    ]
    + [
        "Crypto PriceFeed",
        "Recipe Storage",
        "RPN Calculator",
        "Memory Saver",
        "Currency Converter",
        "Prepear Recipes",
        "eBay Sorter",
        "Spending Tracker",
        "Posture Reminders",
        "Eloqua Contacts",
        "Amazon Research",
        "Breathing Exercise",
        "Recipe Jumper",
        "Sainsbury's Recipes",
        "Base Level",
        "Cooked Wiki",
        "Recipe Skipper",
        "Vitrose Cashback",
        "Twitch Faces",
        "Custom Cursors",
        "YouTube Enhancer",
        "Drawing Saver",
        "Paint Tool",
        "Clicking Game",
        "Browser Piano",
        "Twitch Emotes",
        "Cursor Cats",
        "Stream Previews",
        "1win Mirror",
        "Axie Infinity",
        "YouTube Sync",
        "EA FC WebApp",
        "Kameto Stream",
        "Language Enhancer",
        "Genji Quote",
        "DevBytes News",
        "Metal Pipe Tab",
        "Scott Thumbnails",
        "Snow Customizer",
        "Paramount Party",
        "CSGO Profit",
        "TagPro Alerts",
        "Netanyahu Squidward",
        "InVID Extension",
        "Custom Newsfeed",
        "Protopage Start",
        "14-day Forecast",
        "Weather Forecast",
        "Follow Afar",
        "Techgenyz News",
        "Weather Extension",
        "Send to Kindle",
        "Feed Notifications",
        "News Headlines",
        "Content Insights",
        "infoosite News",
        "Current Weather",
        "NYT Bylines",
        "Libra Hoje",
        "Homentum",
        "Better News",
        "네이버 뉴스 댓글",
        "Billionaire Oligarch",
        "iProfesional Chrome",
        "BazQux Count",
        "Rewards Finder",
        "Kody Cashback",
        "AliExpress Promo",
        "Slickdeals Coupons",
        "AliRadar Finder",
        "Voucher Finder",
        "Price Finder",
        "Выгодные покупки",
        "جيني السعودية تخفيض",
        "Trendyol Discount",
        "Fernz بيتل تخفيض",
        "Coupon Finder",
        "OMG60 Trendyol",
        "بلومنج وير A25",
    ]
    + [
        "Discount Finder",
        "Cashback Rewards",
        "AliExpress Promo Finder",
        "Гисметео Weather",
        "BBC News",
        "Steam Augmentation",
        "Camelcamelcamel Data",
        "Amazon Protection",
        "AliRadar Tool",
        "BigGo Shopping",
        "Universal Gift List",
        "Выгодные покупки",
        "Price Finder",
        "AliExpress Downloader",
        "DSers Sync",
        "LetyShops Cashback",
        "Cuponomia Alerts",
        "Coupon Finder",
        "Ad Speeder",
        "Gmail Mail Merge",
        "Google Meet Enhancer",
        "Price Updates",
        "Online Savings",
        "Cash Back Deals",
        "Slickdeals Coupons",
        "Screen Recorder",
        "ChatGPT LinkedIn",
        "Bubbles Notes",
        "Klarna Cashback",
        "Shopping Alerts",
        "Price Drop Alerts",
        "AAdvantage Miles",
        "Share Email",
        "Cently Savings",
        "Voucher Finder",
        "Cashrewards Alerts",
        "Shopping Simplified",
        "Hashtag Seizer",
        "Coupon Compare",
        "Zola Registry",
        "Picodi Savings",
        "ID.me Discounts",
        "Smarty Coupons",
        "Video Enhancer",
        "Inbox Improvements",
        "Collaborative Agendas",
        "Message Templates",
        "Voice Notes",
        "First Touch",
        "Inclusive Monitoring",
        "WhatsApp Salesforce",
        "BunBox Summarizer",
        "VNPT iAlert",
        "Link Tracker",
        "Speakeasy AI",
        "Personal AI",
        "RedCom Comments",
        "Gmail Tracker",
        "Twitch Voice Notes",
        "Advanced Eyedropper",
        "Full Page Screenshot",
        "JSON Formatter",
        "Redux DevTools",
        "Proxy Manager",
        "Work Balance",
        "HTTP Modifier",
        "Stylus Redesign",
        "CSS Extractor",
        "Site Builder",
        "Query Answer",
        "Screen Tester",
        "URL Redirect",
        "Healthy Metrics",
        "User Script",
        "GitHub Icons",
        "Font Inspector",
        "ABC News",
        "Google Form Copier",
        "Picklist Saver",
        "Netsuite Fields",
        "AEM Extension",
        "Web Scraper",
        "URL Redirect",
        "ProgTest Theme",
        "Recruiting Tool",
        "Epitech Percentage",
        "DigiDive",
        "AirCare Quality",
        "Advent Charts",
        "Website Citations",
        "Knowledge Tool",
        "Google Translate",
        "OpenDyslexic Font",
        "Classroom Slider",
        "Brisk Teaching",
        "Flashcards Translator",
        "Language Netflix",
        "Daily Flashcards",
        "Latency Display",
        "Google Assignments",
        "Chess Skills",
        "AI Copilot",
        "Outwrite Content",
        "Japanese Dictionary",
        "Voice Notes",
        "Bullshit Detector",
        "Duolingo Typing",
        "Jisho Search",
        "NFT Collection",
        "Video Summarizer",
        "Daily Flashcards",
        "AverPoint Tool",
        "Quick Code",
        "AIPRM Templates",
        "QR Code",
        "ChatGPT Results",
        "GPT-4 Copilot",
        "xDragon Game",
        "ChatGPT Browser",
        "Screen Recorder",
        "AI Enhancer",
        "GPT-4 Sidebar",
        "TinEye Search",
        "Text Expander",
        "Page Ruler",
        "Web Highlighter",
        "Earth Tab",
        "GPT Copilot",
        "동영상 재생 속도",
        "GetTopTabs",
        "PowerPoint GPT",
        "Expense Manager",
        "Playstore Rankings",
        "Notion Embedder",
        "Medium Unblock",
        "ChartAI Analysis",
        "Thich Calligraphy",
        "Notion Mate",
        "Adobe Acrobat",
        "왁물원 확장",
        "OpenAI Sora",
        "Userscripts",
        "YouTube Ad Block",
        "Focused Dashboard",
        "Private Surfing",
        "DeepL Translate",
        "Block Ads",
        "שומרים על הנפש",
        "YouTube Ads Block",
        "Site Focus",
        "Speed Controller",
        "Auto Refresh",
        "Reddit Modules",
        "TV Alerts Manager",
        "쿠대 중국몰",
        "A1 Screen Share",
        "쿠대 아마존",
        "Palestinian Tab",
        "Realm Organizer",
        "Islamic Widgets",
        "SaaS Customizer",
        "World Clock",
        "Web Search",
        "Relationship Finder",
        "Binary Earnings",
        "NREGA Files",
        "Navigation System",
        "RoPro Tool",
        "Google Calendar BG",
        "Inspiration Tab",
        "VSCO Media",
        "AI Image Tab",
        "Font Identifier",
        "Scott Sheppeard Tab",
        "Maroun Calendar",
        "ModelAgents Tool",
        "Google Albums",
        "Copy Enabler",
        "Image Break",
        "Among Us Wallpapers",
        "New Tab Overwrite",
        "Background Remover",
        "Meet AutoLeave",
        "Ferrari Tab",
        "Animated Cursors",
        "Strava Experience",
        "Best Cursors",
        "Video Sync",
        "Teleparty Watch",
        "Ad AutoSkip",
        "Video Downloader",
        "Video Enhancer",
        "Strava Switcher",
        "YouTube Shuffle",
        "Lyrics Finder",
        "Petoshi Extension",
        "Sync Teleparty",
        "Bursaspor Tab",
        "Zoosp Sports",
        "INTZ Streamers",
        "KIKLIKO GIFs",
        "Fox News",
        "Fantasy Calculator",
        "Team Alerts",
        "LeagueSync",
        "Video Fast Forward",
        "ReYohoho Link",
        "ニコニコ動画 履歴",
        "Box Jumping",
        "Boxel 3D",
        "Basketball Toss",
        "Head Ball Soccer",
        "Lil Rooster Clicker",
        "Color by Number",
        "4x4 Driver",
        "Maze Game",
        "Pinball Space",
        "2D PvP",
        "Police Car",
        "goSupermodel",
        "Steam Finder",
    ]
)
