# fly.toml app configuration file generated for extension-scraper-daily on 2024-05-04T21:31:38-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'plugin-intelligence-backfill-chrome-extension-list'
primary_region = 'sjc'

[build]
  dockerfile = 'Dockerfile'

[env]
  ENV = 'prod'
  PORT = '8080'

[[services]]
  protocol = ''
  internal_port = 0

  [[services.ports]]
    port = 80
    handlers = ['http']

[scale]
  count = 8  # For wayback machine scraping

[[vm]]
  size = 'shared-cpu-1x'
  memory = '256mb'  # For wayback machine scraping
  # memory = '2048mb'  # For when we do the 100,000 list scraping case
