-- Create new table "plugin"
CREATE TABLE public.plugin (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE NULL DEFAULT now(),
    marketplace_name TEXT NOT NULL,  -- Google Workspace, Chrome Extension, etc.
    marketplace_id TEXT NOT NULL,  -- e.g. google_id
    marketplace_link TEXT NULL,

    -- objective fields
    name TEXT NULL,
    logo_link TEXT NULL,
    user_count BIGINT NULL,
    rating TEXT NULL,
    rating_count BIGINT NULL,

    -- derived fields
    pricing_tiers TEXT NULL,
    lowest_paid_tier DECIMAL NULL,
    search_terms TEXT NULL,
    tags TEXT NULL,
    main_integrations TEXT NULL,
    elevator_pitch TEXT NULL,
    overview_summary TEXT NULL,
    revenue_lower_bound BIGINT NULL,
    revenue_upper_bound BIGINT NULL,
    -- TOOD(P2, devx): We might separate revenue stuff into a separate table
    revenue_analysis TEXT NULL,
    openai_thread_id TEXT NULL,

    CONSTRAINT plugin_pkey PRIMARY KEY (id),
    CONSTRAINT unique_marketplace_id UNIQUE (marketplace_name, marketplace_id)
);

-- Insert data into "plugin" from "google_workspace_metadata" and "revenue_estimates"
INSERT INTO public.plugin (
    marketplace_name, marketplace_id, name, logo_link, user_count, rating, rating_count,
    pricing_tiers, lowest_paid_tier, search_terms, tags, main_integrations,
    elevator_pitch, overview_summary, revenue_lower_bound, revenue_upper_bound,
    revenue_analysis, openai_thread_id, marketplace_link
)
SELECT
    'Google Workspace' AS marketplace_name, gwm.google_id AS marketplace_id, re.name, re.logo_link,
    re.user_count, re.rating, re.rating_count, gwm.pricing_tiers, gwm.lowest_paid_tier::decimal,
    gwm.search_terms, gwm.tags, gwm.main_integrations, gwm.elevator_pitch,
    gwm.overview_summary, re.lower_bound, re.upper_bound, re.full_text_analysis,
    re.thread_id, re.link
FROM
    public.google_workspace_metadata gwm
LEFT JOIN
    public.revenue_estimates re
ON
    gwm.google_id = re.google_id;

ALTER TABLE public.plugin ENABLE ROW LEVEL SECURITY;

-- -- Drop the original tables if no longer needed
DROP TABLE public.google_workspace_metadata;
DROP TABLE public.chrome_extension_metadata;
DROP TABLE public.revenue_estimates;
