create table
  public.revenue_estimates (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    -- NOTE: This is a bit hacky, as I want to present an unified leaderboard.
    plugin_type text not null,
    -- google_id is a foreign key to the either Google Add On or Chrome Extension metadata table
    google_id text null,
    lower_bound bigint null,
    upper_bound bigint null,
    -- link is a redundant field, but with it we can omit fetching the scraper data
    link text null,
    full_text_analysis text null,
    -- to possibly continue on the conversation (and also see what was the starting instruction)
    thread_id text null,
    -- TODO(P0, ux): we should scrape the plugin logo url and store it here too
    constraint revenue_estimates_pkey primary key (id),
    constraint unique_plugin_google_id unique (plugin_type, google_id)
  ) tablespace pg_default;


ALTER TABLE public.revenue_estimates ENABLE ROW LEVEL SECURITY;
