create table
  public.google_workspace (
    id bigint generated by default as identity not null,
    created_at timestamp with time zone null default now(),
    google_id text not null,
    p_date date not null,
    name text not null,
    user_count bigint null,
    rating text null,
    rating_count bigint null,
    backlink_count bigint null,
    revenue_estimate text null,
    pricing_tiers_derived text null,
    description text null,
    overview_summary text null,
    pricing text null,
    listing_updated date null,
    link text not null,
    developer_name text null,
    developer_link text null,
    developer_backlink_count bigint null,
    with_drive boolean null,
    with_docs boolean null,
    with_sheets boolean null,
    with_slides boolean null,
    with_forms boolean null,
    with_calendar boolean null,
    with_gmail boolean null,
    with_meet boolean null,
    with_classroom boolean null,
    with_chat boolean null,
    permissions text null,
    reviews text null,
    overview text null,
    constraint google_workspace_pkey primary key (id)
  ) tablespace pg_default;
  ALTER TABLE public.google_workspace ENABLE ROW LEVEL SECURITY;

  CREATE UNIQUE INDEX idx_google_id_p_date ON public.google_workspace (google_id, p_date);