create table
  public.company (
    id bigint generated by default as identity,
    slug text not null,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp without time zone not null default now(),
    display_name text null,
    legal_name text null,
    website_url text null,
    type text null,
    constraint company_pkey primary key (id),
    constraint company_slug_key unique (slug)
  ) tablespace pg_default;

-- boilerplate:

ALTER TABLE public.company ENABLE ROW LEVEL SECURITY;

CREATE TRIGGER update_company_updated_at
BEFORE UPDATE ON public.company
FOR EACH ROW
EXECUTE FUNCTION update_updated_at_column();


-- update other tables with foreign keys:
ALTER TABLE public.plugin ADD COLUMN company_slug TEXT NULL;
