create table
  public.prompt_log (
    id bigint generated by default as identity not null,
    created_at timestamp with time zone not null default now(),
    prompt_hash text not null,
    model text not null,
    prompt text not null,
    result text not null,
    request_time_ms bigint not null default '0'::bigint,
    prompt_tokens bigint not null default '0'::bigint,
    completion_tokens bigint not null default '0'::bigint,
    constraint prompt_log_pkey primary key (id),
    constraint prompt_log_id_key unique (id),
    constraint prompt_log_prompt_model_key UNIQUE (prompt_hash, model)
  ) tablespace pg_default;

ALTER TABLE public.prompt_log ENABLE ROW LEVEL SECURITY;
