create table
  public.chrome_extension_metadata (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone null default now(),
    google_id text not null,
    pricing_tiers text null,
    search_terms text null,
    tags text null,
    main_integrations text null,
    elevator_pitch text null,
    overview_summary text null,
    constraint chrome_extension_metadata_pkey primary key (id),
    constraint chrome_extension_metadata_google_id_key unique (google_id)
  ) tablespace pg_default;
ALTER TABLE public.chrome_extension_metadata ENABLE ROW LEVEL SECURITY;

-- NOTE: Although would be nice to add my use-case with p_date and Postgres requirements doesn't allow me to.
-- ALTER TABLE chrome_extension
-- ADD CONSTRAINT chrome_extension_fkey_google_id FOREIGN KEY (google_id) REFERENCES public.chrome_extension_metadata (google_id);


create table
  public.google_workspace_metadata (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone null default now(),
    google_id text not null,
    pricing_tiers text null,
    search_terms text null,
    tags text null,
    main_integrations text null,
    elevator_pitch text null,
    overview_summary text null,
    constraint google_workspace_metadata_pkey primary key (id),
    constraint google_workspace_metadata_google_id_key unique (google_id)
  ) tablespace pg_default;
ALTER TABLE public.google_workspace_metadata ENABLE ROW LEVEL SECURITY;

-- NOTE: Although would be nice to add my use-case with p_date and Postgres requirements doesn't allow me to.
-- ALTER TABLE google_workspace
-- ADD CONSTRAINT google_workspace_fkey_google_id FOREIGN KEY (google_id) REFERENCES public.google_workspace_metadata (google_id);

-- These were moved to above
ALTER TABLE public.google_workspace
DROP COLUMN backlink_count,
DROP COLUMN developer_backlink_count,
DROP COLUMN overview_summary,
DROP COLUMN pricing_tiers_derived,
DROP COLUMN revenue_estimate;
