create table
  public.chrome_extension (
    id bigint generated by default as identity not null,
    created_at timestamp with time zone null default now(),
    google_id text not null,
    p_date date not null,
    name text not null,
    rating text null,
    rating_count bigint null,
    link text not null,
    description text null,

    landing_page_url text null,
    is_featured boolean null,
    categories text null,
    user_count bigint null,

    overview text null,
    released_version text null,
    listing_updated date null,
    developer_name text null,
    developer_link text null,
    developer_email text null,

    permissions text null,
    constraint chrome_extension_pkey primary key (id)
  ) tablespace pg_default;
  ALTER TABLE public.chrome_extension ENABLE ROW LEVEL SECURITY;

  CREATE UNIQUE INDEX chrome_extension_idx_google_id_p_date ON public.chrome_extension (google_id, p_date);