app = 'extension-scraper-daily'
primary_region = 'sjc'

[build]
  dockerfile = 'Dockerfile'

[env]
  ENV = 'prod'
  PORT = '8080'

[[services]]
  protocol = ''
  internal_port = 0

  [[services.ports]]
    port = 80
    handlers = ['http']

# TODO: Figure out how to set restart policy in fly.toml (there is a command line option)
#  [[services.processes]]
#    restart = "no"  # most likely it failed because of a bug in the code

[scale]
  count = 1

[[vm]]
  size = 'shared-cpu-1x'
  memory = '512mb'
