app = 'extension-scraper-daily'
primary_region = 'sjc'

[build]
  dockerfile = 'Dockerfile'

[env]
  ENV = 'prod'
  PORT = '8080'

[[services]]
  protocol = ''
  internal_port = 0

  [[services.ports]]
    port = 80
    handlers = ['http']

[[vm]]
  size = 'shared-cpu-1x
  memory = '512mb'
