# fmt: off
# From generate_search_terms.py:
GOOGLE_WORKSPACE_SEARCH_TERMS = ['Slack', 'Salesforce', 'Productivity', 'Google sheets', 'Trello', 'Dropbox', 'Asana', 'Hubspot', 'Google drive', 'Zoom', 'Microsoft teams', 'Zendesk', 'Zapier', 'Mailchimp', 'Google docs', 'Collaboration', 'Automation', 'Gmail', 'Jira', 'Shopify', 'Google workspace', 'Integration', 'Quickbooks', 'Education', 'Box', 'Microsoft excel', 'Ai', 'Google forms', 'Github', 'Wordpress', 'Google slides', 'Communication', 'Google calendar', 'Outlook', 'Crm', 'Email', 'Data analysis', 'Microsoft office', 'Evernote', 'Google classroom', 'Linkedin', 'Microsoft word', 'Facebook', 'Marketing', 'Presentation', 'Security', 'Canva', 'Project management', 'Microsoft 365', 'Data management', 'Analytics', 'Data integration', 'Woocommerce', 'Twitter', 'Task management', 'Microsoft office 365', 'Seo', 'Reporting', 'Instagram', 'Calendar', 'Onedrive', 'Sales', 'Document management', 'Tableau', 'Canvas', 'Notion', 'Microsoft dynamics', 'Google analytics', 'Pdf', 'Microsoft outlook', 'Airtable', 'Magento', 'Adobe creative cloud', 'Stripe', 'Servicenow', 'G suite', 'Efficiency', 'Xero', 'Wix', 'Squarespace', 'Oracle', 'Moodle', 'Intercom', 'Finance', 'Schoology', 'Sap', 'Translation', 'Email marketing', 'Chrome', 'Pipedrive', 'Facebook ads', 'Excel', 'Visualization', 'Notifications', 'Writing', 'Scheduling', 'Paypal', 'Firefox', 'File management', 'Blackboard', 'Accounting', 'Google chat', 'Customization', 'Add-on', 'Marketo', 'Mail merge', 'Email integration', 'Power bi', 'Microsoft powerpoint', 'Google ads', 'Data visualization', 'Spreadsheet', 'Forms', 'Youtube', 'Email management', 'Zoho crm', 'Microsoft onedrive', 'Google contacts', 'Google apps', 'Contact management', 'Safari', 'Keynote', 'Language', 'Content creation', 'Whatsapp', 'Privacy', 'Invoicing', 'Business', 'Bigcommerce', 'Time tracking', 'Templates', 'Team collaboration', 'Small business', 'Workflow automation', 'Qr code', 'Pinterest', 'Compliance', 'Prezi', 'Mysql', 'Data extraction', 'Social media', 'Okta', 'Design', 'Workflow', 'Grammarly', 'Google maps', 'Feedback', 'Chatgpt', 'Aws', 'Workday', 'Monday.com', 'E-commerce', 'Docusign', 'Data import', 'Bitbucket', 'Amazon', 'Powerpoint', 'Joomla', 'Data collection', 'Confluence', 'Management', 'Edge', 'Customer support', 'Adobe acrobat', 'Organization', 'Linkedin ads', 'Lead generation', 'Images', 'Ie10+', 'Hr', 'File sharing', 'Data security', 'Apple mail', 'Yahoo finance', 'Weebly', 'Vimeo', 'Recruitment', 'Quiz', 'Openai', 'Netsuite', 'Google meet', 'Freshbooks', 'Backup', 'Adobe sign', 'Zoho', 'Quizzes', 'Quickbooks online', 'Powerschool', 'Online tool', 'Monitoring', 'Google integration', 'Google', 'Form builder', 'Cloud storage', 'Thunderbird', 'Semrush', 'Research', 'Qr codes', 'Productivity tool', 'Prestashop', 'Plugin', 'Latex', 'Interactive', 'Gsuite', 'Expense management', 'Drupal', 'Documents', 'Calendar integration', 'Analysis', 'Yahoo mail', 'Video conferencing', 'Stocks', 'Square', 'Saas', 'Reports', 'Math', 'Mapping', 'Icons', 'Icloud', 'File conversion', 'Events', 'Etsy', 'Email verification', 'Document signing', 'Document generation', 'Database', 'Data protection', 'Constant contact', 'Workflow management', 'Twilio', 'Survey', 'Sms', 'Optimization', 'Music', 'Google spreadsheets', 'Google sheets add-on', 'Google search console', 'Google drive integration', 'Gmail add-on', 'Gitlab', 'Generator', 'Figma', 'Encryption', 'Email tracking', 'Email notifications', 'Edmodo', 'Editor', 'Drive', 'Discord', 'Data sync', 'Data export', 'Data connector', 'Cryptocurrency', 'Converter', 'Chrome extension', 'Branding', 'Azure', 'Assessment', 'Apple numbers', 'Apple calendar', 'Ahrefs', 'Activecampaign', 'Zoho books', 'Video', 'Typeform', 'Surveys', 'Slides', 'Scrivener', 'Postgresql', 'Pdf conversion', 'Outreach', 'Office 365', 'Moz', 'Libreoffice', 'Inventory management', 'Image editing', 'Html', 'Crm systems', 'Crm integration', 'Content optimization', 'Clever', 'Classroom management', 'Api', 'Adp', 'Accessibility', 'Zotero', 'Transcription', 'Tracking', 'Tool', 'Time management', 'Surveymonkey', 'Spotify', 'Sketch', 'Presentations', 'Pdf editor', 'Multimedia', 'Multilingual', 'Messaging', 'Investment', 'Interactive learning', 'Gmail integration', 'Formatting', 'Event management', 'Erp', 'Employee engagement', 'Ebay', 'Diagramming', 'Deepl', 'Data', 'Csv', 'Contacts', 'Bigquery', 'Android', 'Zoho show', 'Workspace', 'Website builder', 'Webex', 'Visual content', 'User management', 'Tiktok', 'Snowflake', 'Sheets', 'Photo editing', 'Pdf converter', 'Ocr', 'Mendeley', 'Meetings', 'Language support', 'Language learning', 'Json', 'Haiku deck', 'Grammar', 'Gpt-4', 'Google tasks', 'Google chrome', 'Freshdesk', 'Diagram', 'Data transfer', 'Data privacy', 'Conversion', 'Chatbot', 'Attendance tracking', 'Atlassian', 'Adobe creative suite', 'Virtual meetings', 'Viewer', 'Url shortener', 'Td ameritrade', 'Synchronization', 'Sql', 'Seesaw', 'Pdf generation', 'Pardot', 'Mobile app', 'Microsoft sql server', 'Machine learning', 'Localization', 'Ios', 'Interactive brokers', 'Insights', 'Image', 'Google spreadsheet', 'Google data studio', 'Forecasting', 'File viewer', 'File converter', 'Equations', 'Enterprise', 'Engagement', 'Employee recognition', 'Emojis', 'Email security', 'Editing', 'Document viewer', 'Document editing', 'Docs', 'Digital marketing', 'Data enrichment', 'Customer relationship management', 'Coinbase', 'Cloud-based', 'Campaign management', 'Budgeting', 'Browser plugin', 'Booking', 'Binance', 'Audio', 'Api connector', 'Zoho sheets', 'Zoho mail', 'Writing assistant', 'Windows', 'Video editing', 'Travel', 'Text analysis', 'Teacher tools', 'Student engagement', 'Soundcloud', 'Skype', 'Sendgrid', 'Sage', 'Proofreading', 'Pinterest ads', 'Pdf editing', 'Payment processing', 'Overleaf', 'Mind mapping', 'Microsoft azure', 'Majestic', 'Looker', 'Legal', 'Kraken', 'Insightly', 'Infinite campus', 'Import', 'Image processing', 'Grading', 'Google translate', 'Google sheets integration', 'Google photos', 'Gmail plugin', 'Gemini', 'Financial data', 'Esignature', 'Endnote', 'Email finder', 'Email automation', 'Ecommerce', 'E-signature', 'Documentation', 'Digital signature', 'Data processing', 'Data organization', 'Customer service', 'Creativity', 'Content generation', 'Classroom', 'Business intelligence', 'Barcode', 'B2b', 'Ai technology', 'Access control', 'Xml', 'Workflow optimization', 'Word', 'Web scraping', 'Wave', 'Visuals', 'Visme', 'Uml', 'Tradingview', 'Text editing', 'Telegram', 'Splunk', 'Snapchat', 'Slideshare', 'Screaming frog', 'Sage intacct', 'Saas management', 'Redshift', 'Reddit', 'Product management', 'Postgres', 'Png', 'Pexels', 'Pdf viewer', 'Opencart', 'Online tools', 'Mp3', 'Meeting management', 'Meeting', 'Markdown', 'Leave management', 'Keyword research', 'Intranet', 'Infusionsoft', 'Hr management', 'Hootsuite', 'Graphic design', 'Google form', 'Google apps script', 'G suite marketplace', 'G suite integration', 'Freshworks', 'Flickr', 'Financial analysis', 'Financial', 'Facebook messenger', 'Facebook insights', 'Email signature', 'Email campaigns', 'Eloqua', 'Electronic signatures', 'Electronic signature', 'Educational', 'E-signatures', 'E-commerce platforms', 'Document merge', 'Diagrams', 'Development', 'Data migration', 'Csv files', 'Crms', 'Citation', 'Chat', 'Charts', 'Calendly', 'Bulk email', 'Bitly', 'Bing ads', 'Billing', 'Bamboohr', 'Autocad', 'Apple music', 'Api integration', 'Amazon ads', 'Alpha vantage', 'Ai-powered', 'Advertising', 'Adobe analytics', 'Ablebits', 'Yoast seo', 'Webcam', 'Web development', 'Videos', 'Validation', 'Twitter ads', 'Turnitin', 'Trading', 'Trade', 'Tiktok ads', 'Text-to-speech', 'Tex', 'Team management', 'Support', 'Spyfu', 'Spreadsheets', 'Spreadsheet integration', 'Spell checker', 'Social media platforms', 'Slido', 'Slidebean', 'Single sign-on', 'Screen recording', 'Sap concur', 'Sales engagement', 'Sales enablement', 'Reminders', 'Reminder', 'Refworks', 'Reading', 'Python', 'Prowritingaid', 'Professional', 'Productivity tools', 'Piktochart', 'Phishing protection', 'Personalization', 'Pdfs', 'Pdf tools', 'Payroll', 'Openoffice', 'Online learning', 'Onenote', 'No-code', 'Nlp', 'Ms word', 'Microsoft forms', 'Merge', 'Mentimeter', 'Meeting scheduler', 'Medium business', 'Mathematics', 'Lucidchart', 'Logistics', 'Live chat', 'Ip phone systems', 'Integrations', 'Instagram insights', 'Indeed', 'Image viewer', 'Image generation', 'Image enhancement', 'Ibm notes', 'Ibm cloud', 'Hr software', 'Google translate api', 'Google sites', 'Google sheets™', 'Google drive™', 'Google calendar integration', 'Google add-on', 'Gifs', 'Gif', 'Geocoding', 'Gantt chart', 'Form management', 'Financial management', 'Export', 'Eventbrite', 'Emulator', 'Employee management', 'Email signatures', 'E', 'Dropbox paper', 'Docx', 'Document formatting', 'Document creation', 'Document conversion', 'Document automation', 'Data studio', 'Data quality', 'Data manipulation', 'Data insights', 'Data conversion', 'Data cleaning', 'Data analytics', 'Crypto', 'Copper', 'Convertkit', 'Contract management', 'Contacts management', 'Concur', 'Coingecko', 'Calculator', 'Business tools', 'Business management', 'Buffer', 'Browser-based', 'Browser extension', 'Brightspace', 'Bookkeeping', 'Bloomberg', 'Blockchain', 'Bibtex', 'Assessments', 'Appointment scheduling', 'Animation', 'Adobe spark', 'Adobe indesign', 'Addon', 'Absence management', 'Zoominfo', 'Zoho sheet', 'Zendesk sell', 'Youtube music', 'Youtube analytics', 'Workspace management', 'Workplace culture', 'Wikipedia', 'Website', 'Web browsers', 'Weather', 'Wcag', 'Wave accounting', 'Visual enhancement', 'Visitor management', 'Video creation', 'Utilities', 'Usps', 'User experience', 'Ups', 'Ultipro', 'Ubersuggest', 'Txt', 'Twitch', 'Tumblr', 'Tsheets', 'Trak platform', 'Tools', 'Tidal', 'Text editor', 'Teachers', 'Talent management', 'Tables', 'Syntax highlighting', 'Sync', 'Sugarcrm', 'Subscription management', 'Sublime text', 'Stock photos', 'Stock images', 'Statistics', 'Spelling', 'Spark', 'Software development', 'Smtp', 'Sms notifications', 'Smartsheet', 'Sketchup', 'Sites', 'Signature', 'Sharepoint', 'Sentiment analysis', 'Sendinblue', 'Sem', 'Segment', 'Scrum', 'Science', 'Scheduler', 'Salesforce.com', 'Sales teams', 'Sakai', 'Route optimization', 'Robinhood', 'Rest api', 'Response management', 'Response limits', 'Remote work', 'Recovery', 'Recognition', 'Real estate', 'Quotes', 'Quiz builder', 'Programming', 'Printing', 'Portfolio tracking', 'Poll everywhere', 'Playlist', 'Plagiarism detection', 'Plagiarism checker', 'Phishing', 'Personalized', 'Payment', 'Password recovery', 'Pandora', 'Pagerduty', 'Organizational chart', 'Order management', 'Oracle database', 'Opera mail', 'Opera', 'Online booking', 'Nimble', 'Nasdaq', 'Myob', 'Monster', 'Mongodb', 'Mobile devices', 'Mistral', 'Migration', 'Microsoft project', 'Microsoft power automate', 'Microsoft onenote', 'Microsoft exchange', 'Microsoft advertising', 'Microsoft', 'Marketing platforms', 'Mapbox', 'Manufacturing', 'Llama', 'Link management', 'Learning', 'Lead management', 'Labels', 'Kronos', 'Knowledge sharing', 'Klaviyo', 'Jenkins', 'It service management', 'Iphone', 'Investing', 'Inventory', 'Inclusivity', 'Incident response', 'Incident management', 'Image files', 'Image capture', 'Illustrations', 'Ifttt', 'Ie11+', 'Ibm watson', 'Historical data', 'Hiring', 'Hemingway', 'Healthcare', 'Hangouts chat', 'Gusto', 'Graphics', 'Grammar checker', 'Google workspace marketplace', 'Google workspace integration', 'Google tag manager', 'Google presentations', 'Google my business', 'Google material design', 'Google groups', 'Google forms add-on', 'Google cloud sql', 'Google cloud', 'Google bigquery', 'Google assistant', 'Google analytics 4', 'Glassdoor', 'Gimp', 'Geolocation', 'Gaming', 'Gamification', 'G-suite', 'Fuzzy matching', 'Ftp', 'Freshsales', 'Freelancers', 'Free', 'Form publisher', 'Font awesome', 'Flipgrid', 'Fitness', 'Final draft', 'Final cut pro', 'Files', 'File extraction', 'Fidelity', 'Fedex', 'Fax', 'Expensify', 'Exchange server', 'Event registration', 'Epub', 'Entertainment', 'Email marketing platforms', 'Elementor', 'Ebooks', 'Download', 'Document security', 'Docker', 'Divi', 'Digital signatures', 'Digital asset management', 'Developer tools', 'Desire2learn', 'Deezer', 'Data synchronization', 'Data reporting', 'Data generation', 'Dailymotion', 'Customer management', 'Csv data export', 'Coreldraw', 'Content writing', 'Content marketing', 'Content management', 'Contact sharing', 'Connector', 'Compression', 'Compiler', 'Coda', 'Cloud security', 'Claude 3', 'Cisco webex', 'Cisco', 'Choice eliminator', 'Chat integration', 'Charles schwab', 'Certificates', 'Celtx', 'Cc0 license', 'Capterra', 'Calendars', 'Calendar management', 'Buzzsumo', 'Bulk emails', 'Brandfolder', 'Bloomberg terminal', 'Blogging', 'Bitfinex', 'Bing', 'Basecamp', 'Barcode scanning', 'Banking', 'Awesome table', 'Aweber', 'Avery', 'Autocrat', 'Audio editing', 'Audio conversion', 'Attendance', 'Aso', 'Artificial intelligence', 'Apache openoffice', 'Aol mail', 'Amazon web services', 'Amazon seller central', 'Amazon s3', 'Amazon music', 'Amazon fba', 'Alexa', 'Alerts', 'Airbnb', 'Ai tools', 'Ai tool', 'Ai integration', 'Advertising platforms', 'Adobe premiere pro', 'Active directory', 'Accounting systems', 'Academic', 'Zoho invoice', 'Zoho docs', 'Zoho desk', 'Zoho analytics', 'Ziprecruiter', 'Yoast', 'Yesware', 'Yandex', 'Yahoo calendar', 'Xlsx', 'Wufoo', 'Writerduet', 'Wps office', 'Workplace', 'Wordpress plugin', 'Word cloud', 'Wolfram alpha', 'Wells fargo', 'Website optimization', 'Website monitoring', 'Website creation', 'Website analysis', 'Webhooks', 'Webflow', 'Webassembly', 'Web design', 'Web analytics', 'Voice recording', 'Voice recorder', 'Vocabulary', 'Visual collaboration', 'Video conversion', 'Verification', 'Venmo', 'Vendor management', 'Vcard', 'Utility', 'User profile', 'Us bank', 'Us', 'Url', 'Unsplash', 'Ukg dimensions', 'Uber', 'Tripadvisor', 'Translator', 'Translations', 'Topaz signature pads', 'Timer', 'Time-saving', 'Time-off', 'Tiller money feeds', 'Ticketing system', 'Threat detection', 'Thinkorswim', 'Text to speech', 'Text highlighting', 'Text generation', 'Text formatting', 'Text extraction', 'Telecrm', 'Technical writing', 'Teamwork', 'Team efficiency', 'Td bank', 'Task manager', 'Table of contents', 'Table conversion', 'Syncwith', 'Syncing', 'Sustainability', 'Supply chain', 'Supermetrics', 'Suitecrm', 'Students', 'Student management', 'Strategy', 'Storage management', 'Stock market', 'Stock analysis', 'Stickers', 'Sqlite', 'Spreadsheet tool', 'Sony vegas pro', 'Social', 'Snov.io', 'Smb', 'Smartmonkey planner', 'Small businesses', 'Similarweb', 'Signatures', 'Shipping', 'Shipper 360', 'Sheet management', 'Sharing', 'Sharelatex', 'Shared contacts', 'Service', 'Serpstat', 'Seo tools', 'Sefaria', 'Secure', 'Search tool', 'Search and replace', 'Search', 'Screenwriting', 'Screenplay', 'Scratch', 'Schwab', 'School', 'Salesloft', 'Salesforce integration', 'Sales tools', 'Sales performance', 'Sales intelligence', 'Rtf', 'Royalty free', 'Reviso api', 'Reuters', 'Retro', 'Resource allocation', 'Reservation', 'Replicon', 'Remote teams', 'Registration', 'Refme', 'Real-time updates', 'Real-time monitoring', 'Real-time data', 'Read receipts', 'Razorpay', 'Randomizer', 'Random data', 'Quiz generation', 'Quickbooks integration', 'Quandl', 'Qr code generator', 'Qlik', 'Puzzle', 'Public domain', 'Prototyping', 'Protonmail', 'Prospecting', 'Project management tools', 'Problem-solving', 'Pricing', 'Predictions', 'Ppc', 'Powtoon', 'Power automate', 'Portfolio management', 'Podcasts', 'Pnc bank', 'Planning', 'Plagiarism', 'Pixlr', 'Pixabay', 'Photo enhancement', 'Photo editor', 'Phantombuster', 'Personal finance', 'Perplexity', 'Performance reviews', 'Performance', 'Pdf tool', 'Payments', 'Payment collection', 'Package tracking', 'Org chart', 'Orders', 'Oracle sales cloud', 'Options', 'Optimization tool', 'Opsgenie', 'Openai api', 'Open ai', 'Online testing', 'Online meetings', 'Online marketing', 'Online forms', 'Online fax', 'Onelogin', 'Omnichannel', 'Offline', 'Odt', 'Note-taking', 'Non-google integrations not specified', 'Ninjatrader', 'Newsletter', 'News', 'Netflix', 'Navigation', 'Napster', 'Multi-lingual', 'Ms teams', 'Ms powerpoint', 'Ms office', 'Morningstar', 'Mobile apps', 'Mobile', 'Microsoft translator', 'Microsoft power bi', 'Microsoft bing', 'Microsoft active directory', 'Metrics', 'Metatrader', 'Merging', 'Meeting tool', 'Meeting scheduling', 'Meet', 'Medium', 'Mathtype', 'Marketplace', 'Marketing tool', 'Marketers', 'Market research', 'Market data', 'Maps', 'Make', 'Mailing', 'Mailgun', 'Mailbird', 'Macros', 'Macos', 'Lusha', 'Location', 'Lms', 'Linkedin sales navigator', 'Lightworks', 'Libreoffice calc', 'Legal software', 'Learning platform', 'Learndash', 'Lead scoring', 'Languagetool', 'Label maker', 'Krita', 'Kpis', 'Knowledge management', 'Knowledge base', 'Keywords', 'Keap', 'K-12', 'Jupyter notebook', 'Jpg', 'Jpeg', 'Jotform', 'Itunes', 'It', 'Ipad', 'Ip addresses', 'Invision', 'Inventory tracking', 'Internet explorer', 'Internal communication', 'Interactive content', 'Integromat', 'Instructors', 'Innovation', 'Inkscape', 'Influencer marketing', 'Import tool', 'Imovie', 'Image manipulation', 'Image management', 'Image insertion', 'Image import', 'Image conversion', 'Iex cloud', 'Identity management', 'Hybrid office', 'Huobi', 'Hunter.io', 'Hunter', 'Hospitality', 'Hipchat', 'Hemingway editor', 'Helpdesk', 'Hcm', 'Hangouts', 'Gsuite integration', 'Growth hacking', 'Group management', 'Grammar correction', 'Grammar check', 'Gpt4', 'Gpt3', 'Gpt-3.5', 'Gpt-3', 'Gpt', 'Gps', 'Gotomeeting', 'Google suite', 'Google slides™', 'Google single sign-on', 'Google play', 'Google pay', 'Google hangouts', 'Google gemini', 'Google g suite', 'Google forms integration', 'Google for education', 'Google fit', 'Google documents', 'Google docs api', 'Google docs add-on', 'Google directory', 'Google cloud platform', 'Google books', 'Google adwords', 'Godaddy', 'Goal tracking', 'Gmail™', 'Giphy', 'Getresponse', 'Geojson', 'Gdpr', 'Gcp', 'Games', 'G2', 'Fundraising', 'Fun', 'Freshworks crm', 'Free tool', 'Fp&a', 'Formulas', 'Formmule', 'Formfacade', 'Form integration', 'Form creation', 'Form approvals', 'Forex', 'Fleet management', 'Flash player', 'Flash', 'Findthatlead', 'Financial tracking', 'Financial modeling', 'Filmora', 'File transfer', 'File storage', 'File organization', 'File encryption', 'Fidelity investments', 'Family', 'Expense tracking', 'Exchange', 'Excel add-on', 'Excalidraw', 'Exam', 'Event organization', 'Event', 'Ethereum', 'Etfs', 'Esignatures', 'Esign', 'Erp systems', 'Employee onboarding', 'Emaze', 'Email parsing', 'Email organization', 'Email lists', 'Email hunter', 'Email discovery', 'Email campaign', 'Elasticsearch', 'Easybib', 'Duolingo', 'Drift', 'Domo', 'Document workflow', 'Document tools', 'Document studio', 'Document processing', 'Document organization', 'Document enhancement', 'Document converter', 'Document collaboration', 'Document', 'Doctopus add-on', 'Doctopus', 'Digital transformation', 'Digital signing', 'Digital badges', 'Dhl', 'Device management', 'Desmos', 'Delivery', 'Decision-making', 'Decision making', 'Debugging', 'Davinci resolve', 'Datadog', 'Databases', 'Data-driven decisions', 'Data verification', 'Data validation', 'Data preparation', 'Data merge', 'Data loss prevention', 'Data backup', 'Data automation', 'D2l brightspace', 'Cybersecurity', 'Customizable', 'Customer engagement', 'Custom functions', 'Custom', 'Currency', 'Cryptocurrencies', 'Crm platforms', 'Countdown', 'Copyscape', 'Coordinates', 'Content editing', 'Content creators', 'Contact enrichment', 'Confidentiality', 'Conference calls', 'Comparison tool', 'Company databases', 'Collaboration tool', 'Coinmarketcap', 'Coding', 'Code formatting', 'Code editor', 'Cnn', 'Cloud migration', 'Cloud integration', 'Cloud applications', 'Cloud', 'Clock', 'Clipboard', 'Clicksend', 'Click2mail', 'Clearbit', 'Claude', 'Classroom support', 'Classic games', 'Citibank', 'Citations', 'Chromebook', 'Chatbots', 'Chase', 'Charting', 'Chargebee', 'Careerbuilder', 'Capital one', 'Canada post', 'Calculation', 'Cad', 'Business travel', 'Business software', 'Business efficiency', 'Business applications', 'Browser tool', 'Boomerang', 'Blogger', 'Blender', 'Bittrex', 'Bitstamp', 'Bing webmaster tools', 'Bibliography', 'Bard', 'Bank of america', 'Avid media composer', 'Auditing', 'Audit', 'Audiobooks', 'Attachments', 'Attachment', 'Ats', 'Atom', 'Assignments', 'Asset management', 'Archiving', 'Approval processes', 'Approval management', 'Approval', 'Appointments', 'Appointment reminders', 'Applicant tracking', 'Apple icloud', 'Apple', 'App store', 'Apollo', 'Apis', 'Anthropic', 'Anonymity', 'Annotation', 'Analytics tools', 'Amazon seller', 'Amazon redshift', 'Ai chatgpt', 'Agile crm', 'Agile', 'Adobe photoshop', 'Adobe flash player', 'Adobe connect', 'Administration', 'Admin tools', 'Adalo', 'Accounting solutions', 'A/b testing', '3d modeling']

CHROME_EXTENSION_SEARCH_TERMS = (
    [
        "Bookmark Manager",
        "Image Viewer",
        "Downloads Access",
        "URL Manager",
        "Vertical Tabs",
        "Roblox Enhancements",
        "Tab Manager",
        "Tab Saver",
        "Student Picker",
        "Ad Blocker",
        "GrowthX",
        "Kabila Wallet",
        "Maps Access",
        "Histogram Tool",
        "MajesticChrome",
        "AI Assistant",
        "Persian Web",
        "Team Names",
        "Code Styling",
        "YouTube Speeder",
        "Sports Tab",
        "Chat UI",
        "URL Loader",
        "Tabs Export",
        "Text Customize",
        "Efficient Blocker",
        "Maps Thumbnails",
        "Endpoint Security",
        "Browser Security",
        "AdBlock",
        "AdBlocker",
        "Social AdBlock",
        "Password Manager",
        "Privacy Checker",
        "Scam Detection",
        "Anti-Tracking",
        "Adblocking",
        "Phishing Protection",
        "VPN Control",
        "Pop-up Blocker",
        "Online Security",
        "Malware Blocker",
        "Email Masking",
        "Password Security",
        "Crypto Protection",
        "User Agent",
        "Crypto Security",
        "Interceptor",
        "Privacy Guard",
        "Password Generator",
        "User Security",
        "Privacy Scanner",
        "Random Email",
        "Password Manager",
        "Privacy Settings",
        "Browser Security",
        "Blockchain Security",
        "Secure Links",
        "AI Safety",
        "Message Privacy",
        "Web3 Safety",
        "Private Search",
        "ChatGPT DLP",
    ]
    + [
        "Location Notifications",
        "Flight Deals",
        "Booking Copier",
        "Travel Guide",
        "Vacation Bookings",
        "Da Nang News",
        "Flight Info",
        "City Attractions",
        "Taxi Booking",
        "Visa Appointment",
        "Visa Reservation",
        "Points Calculator",
        "Quran Tab",
        "Fundraiser Distribution",
        "Tree Planting",
        "Live Music",
        "Journal Tracker",
        "NSFW Blocker",
        "Self Tracking",
        "Break Reminder",
        "Well-being Tips",
        "Exercise Discovery",
        "Mute Keywords",
        "Mindfulness Reminder",
        "Inspirational Quotes",
        "Wisdom Wheel",
        "Biblical Insights",
        "Break Alerts",
        "Affirmation Creator",
        "Mood Booster",
        "YouTube Volume",
        "Blue Light Filter",
        "Financial Tool",
        "Mental Health",
        "Aion Extension",
        "Calm Tab",
        "Hydration Reminder",
        "Adhkar Popups",
        "Nur Extension",
        "Health Tips",
        "Daily Tarot",
        "DeedDiary",
        "Dark Mode",
        "Text Speech",
        "Video Speed",
        "Right Click Unblock",
        "Font Finder",
        "Roblox Tools",
        "Social AdBlocker",
        "Sound Equalizer",
        "PiP Mode",
        "VPN Access",
        "Text Translator",
        "Roblox Enhancement",
        "Web Reader",
        "Flash Player",
        "Talking Keyboard",
        "Cookie Warning",
        "Korean Localizer",
        "Pokémon Showdown",
        "Accessibility Tool",
        "Asset Portal",
        "Playlist Duration",
        "Payday Loans",
        "Text Speech",
        "Meet Zoom",
        "RTL Alignment",
        "Forum Features",
        "KLMS Redesign",
        "Video Control",
        "HR Glossary",
        "Zalo Tools",
        "PJE Browser",
        "Cookie Management",
        "File Verification",
        "Tab Manager",
        "Tabs Organizer",
        "Voice Expansion",
        "New Tab",
        "Video Downloader",
        "Cookie Acceptance",
        "New Tab Dashboard",
        "Calendar Dark Mode",
        "Cẩm nang du lịch",
        "Công cụ tin tức",
        "BOKA DIN TAXI",
        "Быстрая запись",
        "Помощь в резервировании",
        "나랏말이 POE",
        "Tự động thêm bạn zalo",
        "Extensão gratuita",
        "Központi Azonosító",
    ]
    + [
        "Rate Alerts",
        "Chinese Tools",
        "News Access",
        "Klarna Shopping",
        "Save Online",
        "Cash Back",
        "Pricing History",
        "LetyShops Cashback",
        "Seller Protection",
        "Coupon Finder",
        "Cuponomia Alerts",
        "Online Coupons",
        "Price Comparison",
        "Steam Augmentation",
        "Miles Activation",
        "BigGo Assistant",
        "Universal List",
        "Cently Savings",
        "Cashrewards Alert",
        "Shopping Simplified",
        "Aliexpress Tools",
        "Price Comparison",
        "Social Blade",
        "Picodi Savings",
        "ID.me Discounts",
        "Zola Registry",
        "Smarty Coupons",
        "DSers Sync",
        "Trendyol Discount",
        "Gift Cards",
        "Dropshipping Tool",
        "Loyalty Connection",
        "Shopping Tab",
        "Duos Discount",
        "Facebook Cartzy",
        "AliExpress Search",
        "Social Media Saver",
        "SoleBack Cashback",
        "KAERU Tool",
        "Poly CashBack",
        "Shopping Lists",
        "Kupp Alerts",
        "Naseem Discount",
        "Trendyol Coupon",
        "Scout Helper",
        "ZeroCarbon Impact",
        "Airport Discount",
        "Alibo.vn",
        "Skype Meetings",
        "WhatsApp Tools",
        "Twitch Enhancement",
        "Content Tool",
        "Unblock Sites",
        "Sync Play",
        "Hidden Messages",
        "Link Generator",
        "Instagram Browser",
        "Instagram Scheduler",
        "Web Annotation",
        "YouTube Sync",
        "Instagram Downloader",
        "Facebook Fixer",
        "LinkedIn Prospecting",
        "Meet Attendance",
        "Instagram Desktop",
        "Houzz Ideas",
        "Twitter Enhancer",
        "WhatsApp AI",
        "Facebook Downloader",
        "Facebook AI",
        "Chrome Tab Closer",
        "Instagram Leads",
        "Instagram Leads Pro",
        "Friend Expander",
        "Profile NFT",
        "Ọc Ọc",
        "BluLink CRM",
        "AI Posting Helper",
        "Forocoches",
        "WhatsApp Scraper",
        "Selling Collab",
        "Custom Messages",
        "YouTube Localization",
        "Better Choices",
        "SAKUGABOORU Enhancer",
        "LinkedIn Automation",
        "Alchemy Software",
        "Travel Ideas",
        "Flight Comparison",
        "Wanderlust App",
        "Hotel Discounts",
        "Interactive Maps",
        "Hotel Comparison",
        "Airbnb Comparison",
        "Luxury Travel",
        "Rental Comparison",
        "Hotel Search",
        "Travel Helper",
        "Hotel Direct Price",
        "Radio Wanderlust",
        "Education District",
    ]
    + [
        "Form Filler",
        "xPath Plugin",
        "Open Source Design",
        "SEO Report",
        "nofollow Detector",
        "Research Access",
        "Android Downloader",
        "Docs Analyzer",
        "SEO Tools",
        "Tag Manager Size",
        "NFT Shopping",
        "Loadium Extension",
        "Webflow Productivity",
        "Message Connector",
        "Browser Mockup",
        "ACF Helper",
        "Tags Helper",
        "Freelancer Rank",
        "HubSpot Features",
        "Javascript Injector",
        "Ad Analysis",
        "RevenueBot Functionality",
        "Analytics Inspector",
        "Functionize Tool",
        "Screenshot Tool",
        "Input Tools",
        "Translation Viewer",
        "Developer Toolbox",
        "Citation Generator",
        "Translator Dictionary",
        "Scholar Access",
        "Citations Generator",
        "Attendance Saver",
        "Language Learning",
        "Web Annotation",
        "Lingualeo Translator",
        "LingQ Importer",
        "Trancy Subtitles",
        "Video Notes",
        "Academic Proofreading",
        "Flashcard Importer",
        "Knowledge Base",
        "Recipe Converter",
        "Translation Comparison",
        "한글 자막",
        "Literary Sites",
        "MVP Experience",
        "Turkmen Dictionary",
        "Canvas Tools",
        "Math Tutor",
        "Educational Materials",
        "UCSB Helper",
        "Language Learning",
        "Georgian Schedule",
        "Video Looper",
        "ZTM Extension",
        "Blockchain Security",
        "Search ChatGPT",
        "Learning Companion",
        "Kanji Highlighter",
        "Grammar Fix",
        "Grade Calculator",
        "Danmaku Display",
        "NCERT Books",
        "Bangla Translation",
        "NCERT Books Hindi",
        "Site Logging",
        "Math Solutions",
        "Ferrari Cursor",
        "Music Identifier",
        "Definitions Viewer",
        "42 Enhancements",
        "Twitch Enhancer",
        "Multisig Wallet",
        "PDF Tools",
        "Ecosia Search",
        "Screenshot Tool",
        "Content Summarizer",
        "Printer-Friendly Pages",
        "Email Finder",
        "Pitch Shifter",
        "CS:GO Analyzer",
        "Captcha Solver",
        "Canvas Features",
        "AI Agent Chrome",
        "Job Applications",
        "Trading Companion",
        "Youtube Enhancer",
        "B2B Contacts",
        "PandaWallet",
        "Meeting Controls",
        "AI Video Maker",
        "Premier Search",
        "Twitter Plugin",
        "Contact Finder",
        "Job Tracker",
        "Credentials Wallet",
        "Amazon Extension",
        "AVM Wallet",
        "Data Insights",
        "Product Analysis",
        "AI Youtube Summarizer",
        "Auto Trading",
        "Privacy Search",
        "Wildberries Tools",
        "Web3 Search",
        "Ad Blocker",
        "Remote Desktop",
        "Zoom Scheduler",
        "Google Keep",
        "Search Results",
        "Pinterest Save",
        "Google Drive Save",
        "Google Office",
        "Speedtest",
        "ChatGPT Access",
        "Digital Signature",
        "GenAI Tools",
        "Volume Booster",
        "Notion Clipper",
        "Steam Enhancer",
        "Password Manager",
        "Password Storage",
        "Sound Booster",
        "PDF Viewer",
        "Stanford Fun",
        "Translator",
        "Weather Forecast",
        "UI Tests",
        "Global Collector",
        "KISer Quotes",
        "Douyu Enhancer",
        "Music Links",
        "McGill Enhancer",
        "AliExpress Downloader",
        "Foodify Recipes",
        "Movie Links",
        "Candidate Sourcing",
        "Task Buddy",
        "Interactive Feedback",
        "Alibaba Search",
        "Cryptocurrency Insights",
        "Free Technologies",
        "MSDN Localization",
        "Image Download",
        "Image Download",
        "Image Info",
        "Image Downloader",
        "Sumopaint",
        "Unsplash Photos",
        "Imgur Upload",
        "Image Download",
        "Anime Wallpaper",
        "Customizable Tab",
        "Goku Wallpapers",
        "Neon Space Wallpapers",
        "Art Wallpapers",
        "Google Images",
        "Mandala Drawing",
        "Batch Downloader",
        "Photo Editor",
        "Space Images",
        "Speed Dial",
        "Content Curator",
        "Block Media",
        "Photo Editor",
        "FIFA Wallpapers",
        "One Piece Wallpapers",
        "Digital Art",
        "Blur Disable",
        "Color Tool",
        "Cartoonize Photo",
        "Outdoor Inspiration",
    ]
    + [
        "Crypto PriceFeed",
        "Recipe Storage",
        "RPN Calculator",
        "Memory Saver",
        "Currency Converter",
        "Prepear Recipes",
        "eBay Sorter",
        "Spending Tracker",
        "Posture Reminders",
        "Eloqua Contacts",
        "Amazon Research",
        "Breathing Exercise",
        "Recipe Jumper",
        "Sainsbury's Recipes",
        "Base Level",
        "Cooked Wiki",
        "Recipe Skipper",
        "Vitrose Cashback",
        "Twitch Faces",
        "Custom Cursors",
        "YouTube Enhancer",
        "Drawing Saver",
        "Paint Tool",
        "Clicking Game",
        "Browser Piano",
        "Twitch Emotes",
        "Cursor Cats",
        "Stream Previews",
        "1win Mirror",
        "Axie Infinity",
        "YouTube Sync",
        "EA FC WebApp",
        "Kameto Stream",
        "Language Enhancer",
        "Genji Quote",
        "DevBytes News",
        "Metal Pipe Tab",
        "Scott Thumbnails",
        "Snow Customizer",
        "Paramount Party",
        "CSGO Profit",
        "TagPro Alerts",
        "Netanyahu Squidward",
        "InVID Extension",
        "Custom Newsfeed",
        "Protopage Start",
        "14-day Forecast",
        "Weather Forecast",
        "Follow Afar",
        "Techgenyz News",
        "Weather Extension",
        "Send to Kindle",
        "Feed Notifications",
        "News Headlines",
        "Content Insights",
        "infoosite News",
        "Current Weather",
        "NYT Bylines",
        "Libra Hoje",
        "Homentum",
        "Better News",
        "네이버 뉴스 댓글",
        "Billionaire Oligarch",
        "iProfesional Chrome",
        "BazQux Count",
        "Rewards Finder",
        "Kody Cashback",
        "AliExpress Promo",
        "Slickdeals Coupons",
        "AliRadar Finder",
        "Voucher Finder",
        "Price Finder",
        "Выгодные покупки",
        "جيني السعودية تخفيض",
        "Trendyol Discount",
        "Fernz بيتل تخفيض",
        "Coupon Finder",
        "OMG60 Trendyol",
        "بلومنج وير A25",
    ]
    + [
        "Discount Finder",
        "Cashback Rewards",
        "AliExpress Promo Finder",
        "Гисметео Weather",
        "BBC News",
        "Steam Augmentation",
        "Camelcamelcamel Data",
        "Amazon Protection",
        "AliRadar Tool",
        "BigGo Shopping",
        "Universal Gift List",
        "Выгодные покупки",
        "Price Finder",
        "AliExpress Downloader",
        "DSers Sync",
        "LetyShops Cashback",
        "Cuponomia Alerts",
        "Coupon Finder",
        "Ad Speeder",
        "Gmail Mail Merge",
        "Google Meet Enhancer",
        "Price Updates",
        "Online Savings",
        "Cash Back Deals",
        "Slickdeals Coupons",
        "Screen Recorder",
        "ChatGPT LinkedIn",
        "Bubbles Notes",
        "Klarna Cashback",
        "Shopping Alerts",
        "Price Drop Alerts",
        "AAdvantage Miles",
        "Share Email",
        "Cently Savings",
        "Voucher Finder",
        "Cashrewards Alerts",
        "Shopping Simplified",
        "Hashtag Seizer",
        "Coupon Compare",
        "Zola Registry",
        "Picodi Savings",
        "ID.me Discounts",
        "Smarty Coupons",
        "Video Enhancer",
        "Inbox Improvements",
        "Collaborative Agendas",
        "Message Templates",
        "Voice Notes",
        "First Touch",
        "Inclusive Monitoring",
        "WhatsApp Salesforce",
        "BunBox Summarizer",
        "VNPT iAlert",
        "Link Tracker",
        "Speakeasy AI",
        "Personal AI",
        "RedCom Comments",
        "Gmail Tracker",
        "Twitch Voice Notes",
        "Advanced Eyedropper",
        "Full Page Screenshot",
        "JSON Formatter",
        "Redux DevTools",
        "Proxy Manager",
        "Work Balance",
        "HTTP Modifier",
        "Stylus Redesign",
        "CSS Extractor",
        "Site Builder",
        "Query Answer",
        "Screen Tester",
        "URL Redirect",
        "Healthy Metrics",
        "User Script",
        "GitHub Icons",
        "Font Inspector",
        "ABC News",
        "Google Form Copier",
        "Picklist Saver",
        "Netsuite Fields",
        "AEM Extension",
        "Web Scraper",
        "URL Redirect",
        "ProgTest Theme",
        "Recruiting Tool",
        "Epitech Percentage",
        "DigiDive",
        "AirCare Quality",
        "Advent Charts",
        "Website Citations",
        "Knowledge Tool",
        "Google Translate",
        "OpenDyslexic Font",
        "Classroom Slider",
        "Brisk Teaching",
        "Flashcards Translator",
        "Language Netflix",
        "Daily Flashcards",
        "Latency Display",
        "Google Assignments",
        "Chess Skills",
        "AI Copilot",
        "Outwrite Content",
        "Japanese Dictionary",
        "Voice Notes",
        "Bullshit Detector",
        "Duolingo Typing",
        "Jisho Search",
        "NFT Collection",
        "Video Summarizer",
        "Daily Flashcards",
        "AverPoint Tool",
        "Quick Code",
        "AIPRM Templates",
        "QR Code",
        "ChatGPT Results",
        "GPT-4 Copilot",
        "xDragon Game",
        "ChatGPT Browser",
        "Screen Recorder",
        "AI Enhancer",
        "GPT-4 Sidebar",
        "TinEye Search",
        "Text Expander",
        "Page Ruler",
        "Web Highlighter",
        "Earth Tab",
        "GPT Copilot",
        "동영상 재생 속도",
        "GetTopTabs",
        "PowerPoint GPT",
        "Expense Manager",
        "Playstore Rankings",
        "Notion Embedder",
        "Medium Unblock",
        "ChartAI Analysis",
        "Thich Calligraphy",
        "Notion Mate",
        "Adobe Acrobat",
        "왁물원 확장",
        "OpenAI Sora",
        "Userscripts",
        "YouTube Ad Block",
        "Focused Dashboard",
        "Private Surfing",
        "DeepL Translate",
        "Block Ads",
        "שומרים על הנפש",
        "YouTube Ads Block",
        "Site Focus",
        "Speed Controller",
        "Auto Refresh",
        "Reddit Modules",
        "TV Alerts Manager",
        "쿠대 중국몰",
        "A1 Screen Share",
        "쿠대 아마존",
        "Palestinian Tab",
        "Realm Organizer",
        "Islamic Widgets",
        "SaaS Customizer",
        "World Clock",
        "Web Search",
        "Relationship Finder",
        "Binary Earnings",
        "NREGA Files",
        "Navigation System",
        "RoPro Tool",
        "Google Calendar BG",
        "Inspiration Tab",
        "VSCO Media",
        "AI Image Tab",
        "Font Identifier",
        "Scott Sheppeard Tab",
        "Maroun Calendar",
        "ModelAgents Tool",
        "Google Albums",
        "Copy Enabler",
        "Image Break",
        "Among Us Wallpapers",
        "New Tab Overwrite",
        "Background Remover",
        "Meet AutoLeave",
        "Ferrari Tab",
        "Animated Cursors",
        "Strava Experience",
        "Best Cursors",
        "Video Sync",
        "Teleparty Watch",
        "Ad AutoSkip",
        "Video Downloader",
        "Video Enhancer",
        "Strava Switcher",
        "YouTube Shuffle",
        "Lyrics Finder",
        "Petoshi Extension",
        "Sync Teleparty",
        "Bursaspor Tab",
        "Zoosp Sports",
        "INTZ Streamers",
        "KIKLIKO GIFs",
        "Fox News",
        "Fantasy Calculator",
        "Team Alerts",
        "LeagueSync",
        "Video Fast Forward",
        "ReYohoho Link",
        "ニコニコ動画 履歴",
        "Box Jumping",
        "Boxel 3D",
        "Basketball Toss",
        "Head Ball Soccer",
        "Lil Rooster Clicker",
        "Color by Number",
        "4x4 Driver",
        "Maze Game",
        "Pinball Space",
        "2D PvP",
        "Police Car",
        "goSupermodel",
        "Steam Finder",
    ]
)
